### ISSUE TITLE
Use docs/ as default location for rendered vignettes

### ISSUE THREAD

**Issue by hafen** [hafen/packagedocs#13]
Since you can use `docs/` as the location for gh-pages, maybe this would be a good default for placing the output rather than dealing with a separate gh-pages branch.

**Comment by schloerke** [comment]
build_vignettes defaults to the "_gh-pages" folder.  

I believe leaving it as the gh-pages branch is best.  Then it is not tracked with the master branch and is always reproducible, as it's an automatic response of the current travis push.

Closing for now.
