### ISSUE TITLE
add website description

### ISSUE THREAD

**Issue by schloerke** [hafen/packagedocs#16]
@hafen 

https://hafen.github.io/packagedocs

**Comment by hafen** [comment]
Thanks.  I'm having an issue with the fonts not loading:

<img width="967" alt="screen shot 2016-10-24 at 9 56 03 am" src="https://cloud.githubusercontent.com/assets/1275592/19655245/3083b030-99d0-11e6-9ff0-64f69e6816ba.png">

**Comment by schloerke** [comment]
Make the redirect URL have "https" in it.

It's a cross security issue?

**Comment by schloerke** [comment]
Can this be added to the github url for the project?

http://hafen.github.io/packagedocs/

**Comment by hafen** [comment]
I fixed the fonts issue so that you can use http or https.

**Comment by schloerke** [comment]
![screen shot 2016-11-01 at 11 14 05 pm](https://cloud.githubusercontent.com/assets/93231/19915471/f5a17046-a088-11e6-8b25-b855aae02428.png)

Can you insert the url in the github description?

**Comment by hafen** [comment]
Oh yeah I see. Done.
