### ISSUE TITLE
test before release

### ISSUE THREAD

**Issue by schloerke** [hafen/packagedocs#17]
@hafen 

Master currently works with ggobi/ggally.  Feel free to test on rbokeh

Check out vignettes/docs.Rmd for correct header information.

**Comment by hafen** [comment]
Starting from a fresh package / repo, there are some issues.  To reproduce:

``` r
path <- file.path(tempdir(), "test")

devtools::create(path, description = list(Title = "test", Description = "test package"))
setwd(path)

devtools::use_travis()
devtools::use_mit_license()
devtools::use_github() # this is interactive - need to input to proceed
devtools::use_github_links()

code <- "
#' Test function
#'
#' @param a test
#' @export
a <- function(a = 1) a
"
cat(code, file = "R/test.R")

packagedocs::init_vignettes()
# * Creating `vignettes`.
# * Adding `inst/doc` to ./.gitignore
# * Adding `_gh-pages` to ./.gitignore
# Error in `$<-.data.frame`(`*tmp*`, "title", value = "") : 
#   replacement has 1 row, data has 0

devtools::document()
packagedocs::init_vignettes()
# It appears that './vignettes' has already been initialized.  Overwrite docs.Rmd, rd.Rmd, and rd_index.yaml? (y = yes) y
# * Adding `inst/doc` to ./.gitignore
# * Adding `_gh-pages` to ./.gitignore
# Error in file.path(docs_path, rd_index_file_yaml()) : 
#   could not find function "rd_index_file_yaml"
```

Note that this will create a github repo "test".

@schloerke

**Comment by schloerke** [comment]
correct.  sorry, missed the function removal.

**Comment by schloerke** [comment]
0713087  pull and try again.

**Comment by hafen** [comment]
That fixed the second error - still getting the first error though.

**Comment by hafen** [comment]
I think it just has to do with the edge case of building a yaml when there are no docs generated yet.  Might be good to just give a message / warning in this case.

**Comment by schloerke** [comment]
yes, it's because there are no man files. 

warning and fake shell returned 8af1770

**Comment by hafen** [comment]
Thanks.  What is the minimal scope required for the access key?

<img width="747" alt="screen shot 2016-10-28 at 9 17 08 am" src="https://cloud.githubusercontent.com/assets/1275592/19813603/60095856-9cef-11e6-8710-d43a809ba3ff.png">

**Comment by schloerke** [comment]
public_repo

**Comment by hafen** [comment]
I'm getting the following in `build_win()` but not anywhere else:

```
* checking files in 'vignettes' ... WARNING
Files in the 'vignettes' directory newer than same file in 'inst/doc':
  'docs.html'
```

I've tried quite a few things and cannot figure out how to fix it.  'docs.html' doesn't even exist in vignettes. Any ideas @schloerke?

**Comment by schloerke** [comment]
I've found this. https://github.com/hadley/devtools/issues/1348

I've rebuilt mine and am trying now.

**Comment by schloerke** [comment]
More info to keep updated...

devtools::build() produces are tar.gz file.  This file believes that docs.Rmd is not a vig.  It only believes rd.Rmd is a vig

This issue trickles down to build_win().  The issue is currently at the `devtools::build()` level.

**Comment by schloerke** [comment]
@hafen. Fixed the index_file issue. 

For some reason it is also working in build as well.  Testing on build_win() now

**Comment by schloerke** [comment]
Still fails to fix the docs.Rmd issue with build_win()

```
* checking files in 'vignettes' ... WARNING
Files in the 'vignettes' directory newer than all files in 'inst/doc':
  'docs.Rmd'
```

To make us feel better, lme4 has a lot of issues with this.  I'd say they'd have their stuff together.

https://cran.r-project.org/web/checks/check_results_lme4.html

**Comment by hafen** [comment]
Thanks!

BTW, completely removing my local inst/docs stopped the warning on build_win() for me.

**Comment by hafen** [comment]
Things look good.  Submitted to CRAN

**Comment by schloerke** [comment]
So weird!
