### ISSUE TITLE
validate use_travis

### ISSUE THREAD

**Issue by schloerke** [hafen/packagedocs#19]
@hafen 

0032da3

**Comment by hafen** [comment]
Great!  I'll give it a try.

**Comment by hafen** [comment]
This is good except we also need a check_travis_ci_init function.  If the user hasn't initialized their repo in travis ci, it would be good to provide a note about where to go to do it.  I'm trying to see if there is an option for the `travis` command that will let us check this easily.

**Comment by schloerke** [comment]
Travis settings
Travis enable

**Comment by hafen** [comment]
Thanks. I suppose we could also just try to capture the output of the warning emitted by travis encrypt.  But I can't seem to detect the warning (same is true for travis settings and travis enable).

**Comment by hafen** [comment]
Oh here we go:

``` r
system2("travis", "settings", stderr = TRUE)
```

**Comment by hafen** [comment]
One more thing - is `use_travis` too much of a clash with devtools?  Should I rename it?

**Comment by schloerke** [comment]
Can we call it first?

**Comment by hafen** [comment]
What I'm thinking of is that this will be a function that's used interactively.  The user might actually load both devtools and packagedocs and then call use_travis without prefixing it.  But use_travis is nice and succinct and familiar too though if we can assume people will always use it with packagedocs::use_travis

**Comment by schloerke** [comment]
how about we call it use_travis. and if the .travis.yml file doesn't exist, we call devtools::use_travis

**Comment by hafen** [comment]
Sounds good
