### ISSUE TITLE
init_vignettes() error

### ISSUE THREAD

**Issue by pat-s** [hafen/packagedocs#24]
When calling `init_vignettes()` I get the following error:

```
* Adding `inst/doc` to ./.gitignore
* Adding `_gh-pages` to ./.gitignore
Error in extract2(., keyword_pos) : Index out of bounds
```

In the end `rd_index.yaml` is missing. macOS 10.12

**Comment by hafen** [comment]
It appears there is something in your .Rd files that packagedocs is having trouble with. Is the package you are testing this on publicly available? If so I can take a look.

Alternatively, you can construct your rd_index.yaml manually but that wouldn't be very fun.

**Comment by pat-s** [comment]
Yes it is, check repo '[oddsratio'](https://github.com/pat-s/oddsratio)!

**Comment by lhsego** [comment]
Just installed `packagedocs`:  Same issue:

    > init_vignettes(title = "Smisc", subtitle = "Sego Miscellaneous", author = "Landon Sego")
    * Creating `vignettes`.
    * Adding `inst/doc` to ./.gitignore
    * Adding `_gh-pages` to ./.gitignore
    Error in extract2(., keyword_pos) : subscript out of bounds

lubuntu 17.10, R 3.4.2
