### ISSUE TITLE
Does this package work on Windows?

### ISSUE THREAD

**Issue by dmenne** [hafen/packagedocs#28]
I could not get this package to run on Windows. For example

`system("echo ${#GITHUB_PAT}") `
gives
`$#GITHUB_PAT`

which is not numeric.  Did I miss something?

**Comment by tylerburleigh** [comment]
I think it's not. I'm getting:

`Error in system("which travis", intern = TRUE) : 'which' not found`

After setting `GITHUB_PAT` as an environment variable and invoking `packagedocs::use_travis()`. It seems the package is trying to use a `which` system command which is Linux-specific.

**Comment by dmenne** [comment]
Note that the posting is 15 month old. Closing it now.
