### ISSUE TITLE
add_desc_package not found

### ISSUE THREAD

**Issue by iembry** [hafen/packagedocs#33]
Hi, I already have a package and I used the following 2 commands:

```
packagedocs::init_vignettes()
packagedocs::build_vignettes()
```

This is the result:

```
> packagedocs::init_vignettes()
Registered S3 method overwritten by 'lazyrmd':
method                from
knit_print.htmlwidget htmlwidgets
Error in get(x, envir = ns, inherits = FALSE) :
object 'add_desc_package' not found
```

Can packagedocs be used in an existing package or does it have to be a new packages? Thank you.

**Comment by hafen** [comment]
I'm not sure. I'm not really maintaining this package anymore and would suggest that you take a look at [pkgdown](https://pkgdown.r-lib.org). Thanks!
